<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS-FULL</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>raulmagus@gmail.com;</mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>22ed1754-d40f-45b0-9255-ec5b972fab2e</testSuiteGuid>
   <testCaseLink>
      <guid>c53a52d3-2408-49e8-afda-2d3b7aa02770</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MODULOK_nincs_login_belinkelve/Pacienstorzs/TC-MODUL-Pacienstorzs_paciensfelvetel_full_check</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2e640e8-9b9e-4eb9-b062-5acb64cae5e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68ab02d7-8162-4e58-a571-b43f59e3d861</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4a1a40c-e9a7-4577-9844-9d034a3fae5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c1e9016-0b9a-44b6-b677-802c33366b2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7eaf15b6-8dee-4763-98de-fc5682d3c4c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7bc8b6c3-105f-4982-94d2-675df768e09e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5506d752-3e09-48c7-a750-0f6c711a4b74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cac12d9-8d66-4f1e-9639-96af3fc0053b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c06b119-3d84-4477-8461-585ac4d1410b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68b35435-f128-4ee2-8bfa-4712fb39c4d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4eb0a48-09b3-459c-bce4-17ee53cf38bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24d77ad7-619f-4791-88de-d20d1099bf4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6175a30e-5054-4d1a-a617-14b27c152e55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5e10544-bcae-4bf0-9a2b-f6f7e218feae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57fea748-b2e7-4516-8a87-2a32b8f942be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1bfebbab-7969-4e67-8825-9c736b025aa9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7db5e03-a3d1-4a04-a7c4-07238e317e4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b89b2128-fdb3-4b07-87f4-5d9f3e061569</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb8490c4-06ee-468a-8cde-ead19c50fb96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8ec83806-f2e8-4f24-be74-3000075e55db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MODULOK_nincs_login_belinkelve/Pacienstorzs/TC-MODUL-Pacienstorzs_kereses_torles_ELSO_talalat</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a84291d-0b8c-432c-82d8-7e7726746fd9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1203eb6a-fd5d-409f-902d-fa7d04f05667</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MODULOK_nincs_login_belinkelve/TC-MODUL-Receptek-Gyogyszer</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1e2c07a1-5785-406f-abc3-d7378d22e25f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MODULOK_nincs_login_belinkelve/TC-MODUL-Vizsgalati-lapok</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>40855a61-44d3-4f5e-b648-a00a8e62326d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MODULOK_nincs_login_belinkelve/TC-MODUL-Szamlazas</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c74541e0-729e-480d-8b9d-4b8214724001</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MODULOK_nincs_login_belinkelve/TC-MODUL-Keszlet</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f801fdf4-27f2-463a-9947-9e75985e1e1c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MODULOK_nincs_login_belinkelve/TC-MODUL-Statisztika</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f50a5604-5a87-4c3a-a972-a9f5c32ac7fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MODULOK_nincs_login_belinkelve/Vezerlopult/TC-MODUL--Vezerlopult_All_linked</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>81cd69d5-8617-4888-9aab-c60fbe463095</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MODULOK_nincs_login_belinkelve/Pacienstorzs/TC-MODUL-Pacienstorzs-TAJ-check-EXCELBOL_</testCaseId>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>482dc5d6-1b9d-48b8-99c1-85a79d536baa</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-2</value>
         </iterationEntity>
         <testDataId>Data Files/TD-pacienstorzs</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>482dc5d6-1b9d-48b8-99c1-85a79d536baa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>AZONOSITO</value>
         <variableId>91f8ef2c-4dec-4db5-ba5c-d800ff008f4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>482dc5d6-1b9d-48b8-99c1-85a79d536baa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>elvárt eredmény</value>
         <variableId>372d96b3-9aa3-462e-9525-ea2dcf602365</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>256f2953-17a3-48b1-ac38-23a69b7ea81e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MODULOK_nincs_login_belinkelve/Pacienstorzs/TC-MODUL-Pacienstorzs-SzulDat-check-EXCELBOL</testCaseId>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>3029b95d-ad20-483d-9f83-c6990c59d55c</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>4-5</value>
         </iterationEntity>
         <testDataId>Data Files/TD-pacienstorzs</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>3029b95d-ad20-483d-9f83-c6990c59d55c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>elvárt eredmény</value>
         <variableId>fc9929f9-5f5d-4105-a8b5-81df205ed4cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3029b95d-ad20-483d-9f83-c6990c59d55c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>SZUL_DATUM</value>
         <variableId>641c207c-32f5-45a9-8b48-ff97568ea959</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
