<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Tetel_hozaadasa_Szamlakiallitas</name>
   <tag></tag>
   <elementGuidId>70f18731-0f2e-49d2-8d97-58136b5ffada</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@onclick='openPriceSelector(this)'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ajaxcontent&quot;)/div[@class=&quot;invoice-items&quot;]/div[@class=&quot;invoice-item-group&quot;]/form[@id=&quot;invoice-items&quot;]/table[@id=&quot;cases&quot;]/tbody[1]/tr[@class=&quot;newitem&quot;]/td[@class=&quot;controls centered&quot;]/div[@class=&quot;button&quot;][count(. | //div[@onclick = 'openPriceSelector(this)']) = count(//div[@onclick = 'openPriceSelector(this)'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>openPriceSelector(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
											Tétel hozzáadása
										</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ajaxcontent&quot;)/div[@class=&quot;invoice-items&quot;]/div[@class=&quot;invoice-item-group&quot;]/form[@id=&quot;invoice-items&quot;]/table[@id=&quot;cases&quot;]/tbody[1]/tr[@class=&quot;newitem&quot;]/td[@class=&quot;controls centered&quot;]/div[@class=&quot;button&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@onclick='openPriceSelector(this)'])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//table[@id='cases']/tbody/tr[2]/td/div)[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Szakrendelés'])[2]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kedvezmény'])[2]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/table/tbody/tr[2]/td/div</value>
   </webElementXpaths>
</WebElementEntity>
